#!/bin/bash

# File directory full path
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd ${SCRIPTPATH} # navigate to this directory

# make project, see src/CMakeList.txt
# (it's automatically generated by catkin workspace)
catkin_make

# source global variables which may be needed for project
source devel/setup.sh

# run ROS project loop
roslaunch launch/project.launch